### PR TITLE
Explicitly depend on SWIM target, to prevent SwiftPM dependency issue

### LINKED ISSUE #89: main doesn't compile on Xcode beta 5
### Expected behavior
Latest `main` compiles and runs tests fine with latest Xcode 14 Seed.

### Actual behavior
```
Building for debugging...
/Users/davidnadoba/Repositories/swift-cluster-membership/.build/arm64-apple-macosx/debug/SWIM.build/module.modulemap:2:12: error: header '/Users/davidnadoba/Repositories/swift-cluster-membership/.build/arm64-apple-macosx/debug/SWIM.build/SWIM-Swift.h' not found
    header "/Users/davidnadoba/Repositories/swift-cluster-membership/.build/arm64-apple-macosx/debug/SWIM.build/SWIM-Swift.h"
           ^
/Users/davidnadoba/Repositories/swift-cluster-membership/Tests/SWIMTestKit/TestMetrics.swift:32:18: error: could not build Objective-C module 'SWIM'
@testable import SWIM
                 ^
/Users/davidnadoba/Repositories/swift-cluster-membership/.build/arm64-apple-macosx/debug/SWIM.build/module.modulemap:2:12: error: header '/Users/davidnadoba/Repositories/swift-cluster-membership/.build/arm64-apple-macosx/debug/SWIM.build/SWIM-Swift.h' not found
    header "/Users/davidnadoba/Repositories/swift-cluster-membership/.build/arm64-apple-macosx/debug/SWIM.build/SWIM-Swift.h"
           ^
/Users/davidnadoba/Repositories/swift-cluster-membership/Tests/SWIMTestKit/TestMetrics.swift:32:18: error: could not build Objective-C module 'SWIM'
@testable import SWIM
                 ^
/Users/davidnadoba/Repositories/swift-cluster-membership/.build/arm64-apple-macosx/debug/SWIM.build/module.modulemap:2:12: error: header '/Users/davidnadoba/Repositories/swift-cluster-membership/.build/arm64-apple-macosx/debug/SWIM.build/SWIM-Swift.h' not found
    header "/Users/davidnadoba/Repositories/swift-cluster-membership/.build/arm64-apple-macosx/debug/SWIM.build/SWIM-Swift.h"
           ^
/Users/davidnadoba/Repositories/swift-cluster-membership/Tests/SWIMTestKit/TestMetrics.swift:32:18: error: could not build Objective-C module 'SWIM'
@testable import SWIM
                 ^

error: fatalError
```
### Steps to reproduce
```
git clone git@github.com:apple/swift-cluster-membership.git
cd swift-cluster-membership
swift test
```

### Version/commit hash
latest `main`
`68b2da6afe4491fca3be3f1265a1ee2697f33ff3`

### Swift & OS version (output of `swift --version && uname -a`)
Xcode: Version 14.0 beta 5 (14A5294e)
```
swift-driver version: 1.62.3 Apple Swift version 5.7 (swiftlang-5.7.0.123.8 clang-1400.0.29.50)
Target: arm64-apple-macosx13.0
Darwin Davids-MBP.fritz.box 22.0.0 Darwin Kernel Version 22.0.0: Wed Jul 20 01:53:07 PDT 2022; root:xnu-8792.0.188.141.3~2/DEVELOPMENT_ARM64_T6000 arm64
```

### PR DESCRIPTION
**Pull request by ktoso**
resolves #89

And also enables `--explicit-target-dependency-import-check error` on `main` swift so that such problems never creep in again

### CODE REVIEW

**Comment by ktoso** [comment]
Very good `13:07:39 error: Target SWIMTestKit imports another target (SWIM) in the package without declaring it a dependency.` tho it still runs tests after that meh; but okey

File: Package.swift [hunk 1]
```diff
@@ -93,6 +93,7 @@ var targets: [PackageDescription.Target] = [
     .testTarget(
         name: "SWIMTestKit",
         dependencies: [
+            "SWIM",
```
Comment (ktoso) [inline Package.swift:96]: Hah so interestingly a module doing `import SWIM` but NOT having it as dependency is what caused https://github.com/apple/swift-cluster-membership/issues/89 @dnadoba 

Tho now with `--explicit-target-dependency-import-check error` we'll never get those anymore
